name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.9"
      
      - name: Sync the project
        run: uv sync --all-extras

      - name: Run tests
        run: uv run pytest
        
    