
name: Run Pytest on PR

on:
  pull_request:
    branches: [ main ] # Or your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Or your desired version
      - name: Run Pytest
        run: pytest
